# Generated by Django 4.0.2 on 2023-04-19 15:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('training', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='addr',
            field=models.CharField(max_length=50, verbose_name='Адрес'),
        ),
        migrations.CreateModel(
            name='Training',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Название')),
                ('direction', models.CharField(max_length=50, verbose_name='Направление')),
                ('date', models.DateField(verbose_name='Дата')),
                ('exp', models.BooleanField(verbose_name='Опыт')),
                ('educ', models.BooleanField(verbose_name='Образование')),
                ('idFKCompany', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='training.company')),
            ],
        ),
    ]
