# Generated by Django 4.0.2 on 2023-04-27 06:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('training', '0003_profile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='profilePic',
            field=models.ImageField(upload_to='profilePictures', verbose_name='Изображение профиля'),
        ),
    ]
