# Generated by Django 4.0.2 on 2023-05-03 17:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('training', '0005_alter_profile_profilepic'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='profilePic',
            field=models.ImageField(upload_to='media/images/', verbose_name='Изображение профиля'),
        ),
    ]
