# Generated by Django 4.0.2 on 2023-05-03 18:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('training', '0006_alter_profile_profilepic'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='profilePic',
            field=models.ImageField(upload_to='images/', verbose_name='Изображение профиля'),
        ),
    ]
