# Generated by Django 4.0.2 on 2023-05-04 03:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('training', '0007_alter_profile_profilepic'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProfileToCompanies',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='training.company')),
            ],
        ),
        migrations.AddField(
            model_name='profile',
            name='proftocomp',
            field=models.ManyToManyField(through='training.ProfileToCompanies', to='training.Company'),
        ),
        migrations.AddField(
            model_name='profiletocompanies',
            name='profile',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='training.profile'),
        ),
    ]
